import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fellowship Mission of All Nations',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Theme toggle logic
  // This is a simple implementation using localStorage and a button
  // For a more robust solution, consider using context or a library
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-white text-black dark:bg-black dark:text-white transition-colors duration-300">
  {/* ThemeToggle removed from layout. Now only in navigation. */}
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </body>
    </html>
  )
}
